"""Add sub1 column to Response

Revision ID: 28888d3976db
Revises: f9afb921e576
Create Date: 2025-06-13 23:59:36.583981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28888d3976db'
down_revision = 'f9afb921e576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub1', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('sub1')

    # ### end Alembic commands ###
