"""Add form_score column to Response

Revision ID: 7146f3062f9c
Revises: 9b3db59e2844
Create Date: 2025-06-12 01:45:31.873410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7146f3062f9c'
down_revision = '9b3db59e2844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('form_score')

    # ### end Alembic commands ###
