"""Add sub1 column to Response

Revision ID: 79adedfd2b34
Revises: 28888d3976db
Create Date: 2025-06-14 00:49:25.937095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79adedfd2b34'
down_revision = '28888d3976db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sts', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('sts')

    # ### end Alembic commands ###
